name: "SenseCraft"
description: "SenseCraft Model Assistant"
url: "https://github.com/Seeed-Studio/SenseCraft-Web-Toolkit"
version: "1.0.0"
slug: "sensecraft"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
ports:
  443/tcp: 443
  8000/tcp: 9527
ports_description:
  443/tcp: SenseCraft Web Toolkit port
  8000/tcp: SenseCraft API port
webui: "https://[HOST]:[PORT:443]"
panel_icon: mdi:cloud
options: {}
schema: {}
